name: Build & Test

on: [push]

jobs:
  windows-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Run './build.cmd Coverage'
        run: ./build.cmd Coverage
        env:
            GitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: artifacts/coverage-report