name: Publish NuGet packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Run NugetPublish
        run: ./build.sh publish
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}